### ISSUE TITLE
Make sure this works on MacOS

### ISSUE THREAD

**Issue by psychok7** [psychok7/django-yadpt-starter#32]
@pslobo Please test on MacOS

**Comment by pslobo** [comment]
Tested on macOS and is working fine, except for https://github.com/psychok7/django-yadpt-starter/issues/33#issue-211652400

**Comment by psychok7** [comment]
@pslobo do you think de prod version would work on a MacOs machine?? aren't you writing the let's encrypt certs to specific linux paths?

**Comment by pslobo** [comment]
No, certificates are being saved in a named volume that is then mounted on the nginx container too so linux filesystem (or windows filesystem) shouldn't be an issue here.

I think the only thing we need to fix is the setup script. Docker side of things should all work just fine, but we'll only be able to test that once we've fixed the setup script.
