### ISSUE TITLE
Setup utility not working properly when environment is set to dev

### ISSUE THREAD

**Issue by pslobo** [psychok7/django-yadpt-starter#33]
When the environment is set to dev, the setup utility isn't prompting the user for some needed values, namely DOMAIN, and therefore, nginx.conf isn't getting properly setup.

So `server_name  {{DOMAIN}};` is getting set to `server_name ;` and therefore nginx fails to start.

**Comment by pslobo** [comment]
Ignore this. My brain stopped for a moment there. Dev isn't supposed to be using nginx :)

**Comment by psychok7** [comment]
https://github.com/psychok7/django-yadpt-starter/commit/cf1dd996e226e3fc2eac3487c13aebaf35e9074c
