### ISSUE TITLE
Https certs volume not being created

### ISSUE THREAD

**Issue by psychok7** [psychok7/django-yadpt-starter#34]
@pslobo i think we might have to remove this https://github.com/psychok7/django-yadpt-starter/blob/master/minimal/docker-compose.yml#L63 because when i ran the compose build and up on my production machine for the first time, it did not create the https certs volume as it was supposed to and it showed `ERROR: Volume dkl_backoffice_https_certs declared as external, but could not be found. Please create the volume manually using `docker volume create --name=dkl_backoffice_https_certs` and try again.`

I then had a look into my production released sites and in fact none of them had the `external` flag, so the first time they ran they created the appropriate volume.

Do you see any reason to not remove the flag??

**Comment by pslobo** [comment]
The reason it was not found is because the creation of that volume is part of the startup script. When certs are generated. If you don't use the startup script, then you'll have to create the volume by hand.

**Comment by pslobo** [comment]
Check https://github.com/psychok7/django-yadpt-starter/blob/master/minimal/django-yadpt-starter.py#L72 for what I'm referring to.

**Comment by psychok7** [comment]
@pslobo when i got the error i tried running that exact command (with the latest docker) and it did not create the volume. Maybe in newer docker versions you have to be more explicit for creating volumes??

Nevertheless, if we remove the `external` it should work for every case right?

**Comment by psychok7** [comment]
@pslobo fixed it, please test when you get the chance.
